/*******************************************************************************
 * Copyright (c) 2021, 2022 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Eurotech - initial API and implementation
 *******************************************************************************/
package org.eclipse.kapua.service.device.call.kura.model.configuration.json;
// Content with portions generated by generative AI platform

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import org.eclipse.kapua.service.device.call.kura.model.configuration.xml.KuraXmlConfigPropertiesAdapted;
import org.eclipse.kapua.service.device.call.kura.model.configuration.xml.KuraXmlConfigPropertiesAdapter;
import org.eclipse.kapua.service.device.call.kura.model.configuration.xml.XmlConfigPropertyAdapted;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Custom JSON deserializer for Kura configuration properties.<br>
 * This deserializer reads a JSON structure that includes both the property values and their corresponding types, based on the format used in Kura.<br>
 * It converts this JSON structure back into a Map that can be used internally<br>
 * We assume that input JSON adheres to the CONF-V2 format used in Kura, ensuring compatibility with Kura's configuration management.<br>
 *
 * example JSON input for a property named "exampleProperty" of type INTEGER with value 42:
 * {
 * "exampleProperty": {
 * "value": 42,
 * "type": "INTEGER"
 * }
 * }
 *
 * see https://esf.eurotech.com/docs/configuration-v2-rest-apis-and-conf-v2-request-handler#configurationproperties
 *
 * Internally, the deserializer first reads the JSON structure and creates an intermediate representation using XmlConfigPropertyAdapted objects, which are then converted to the final Map format using the KuraXmlConfigPropertiesAdapter unmarshaller.<br>
 * @since 2.1.0
 */
public class KuraJsonConfigPropertiesDeserializer extends JsonDeserializer<Map<String, Object>> {

    private static final String TYPE_FIELD_NAME_JSON = "type";
    private static final String VALUE_FIELD_NAME_JSON = "value";

    @Override
    public Map<String, Object> deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException {
        //initial safeguard to handle null or empty JSON content
        if (jp.getCurrentToken() == null) {
            jp.nextToken();
        }
        if (jp.getCurrentToken() != JsonToken.START_OBJECT) {
            ctxt.reportWrongTokenException(this, JsonToken.START_OBJECT, "Expected START_OBJECT");
        }

        KuraXmlConfigPropertiesAdapted adapted = writeKuraPropertiesFromJsonString(jp);
        return writeMapFromKuraProperties(adapted);
    }

    //read each property and create the corresponding XmlConfigPropertyAdapted object
    private KuraXmlConfigPropertiesAdapted writeKuraPropertiesFromJsonString(JsonParser jp) throws IOException {
        List<XmlConfigPropertyAdapted> adaptedProperties = new ArrayList<>();

        while (jp.nextToken() != JsonToken.END_OBJECT) {
            String propertyName = jp.getCurrentName();
            jp.nextToken();

            XmlConfigPropertyAdapted adaptedProperty = readProperty(jp, propertyName);
            if (adaptedProperty != null) {
                adaptedProperties.add(adaptedProperty);
            }
        }

        KuraXmlConfigPropertiesAdapted adapted = new KuraXmlConfigPropertiesAdapted();
        adapted.setProperties(adaptedProperties.toArray(new XmlConfigPropertyAdapted[0]));
        return adapted;
    }

    //from the XmlConfigPropertyAdapted object creates the Map (effective desrialize/unmarshal)
    private Map<String, Object> writeMapFromKuraProperties(KuraXmlConfigPropertiesAdapted adapted) throws IOException {
        try {
            return new KuraXmlConfigPropertiesAdapter().unmarshal(adapted);
        } catch (Exception e) {
            throw new IOException("Error unmarshalling properties from XML adapted form", e);
        }
    }


    //Note that, in the case the property is a password, the "isEncrypted" field will be false (set by constructor)
    //This is correct, because CONF-V2 DTOs have such properties in clear, not encrypted
    private XmlConfigPropertyAdapted readProperty(JsonParser jp, String propertyName) throws IOException {
        XmlConfigPropertyAdapted property = new XmlConfigPropertyAdapted();
        property.setName(propertyName);

        String typeString = null;
        List<String> values = new ArrayList<>();

        while (jp.nextToken() != JsonToken.END_OBJECT) { //Read the "value" and "type" fields for the property (value could be array)
            String fieldName = jp.getCurrentName();
            jp.nextToken();

            if (VALUE_FIELD_NAME_JSON.equals(fieldName)) {
                if (jp.currentToken() == JsonToken.START_ARRAY) {
                    property.setArray(true);
                    while (jp.nextToken() != JsonToken.END_ARRAY) {
                        values.add(readPrimitiveValue(jp));
                    }
                } else {
                    property.setArray(false);
                    values.add(readPrimitiveValue(jp));
                }
            } else if (TYPE_FIELD_NAME_JSON.equals(fieldName)) {
                typeString = jp.getValueAsString();
            }
        }

        if (typeString != null) {
            property.setType(parseType(typeString)); //parse the type string to the corresponding enum value
        } else {
            property.setType(XmlConfigPropertyAdapted.ConfigPropertyType.stringType);
        }

        property.setValues(values.toArray(new String[0]));

        return property;
    }

    private String readPrimitiveValue(JsonParser jp) throws IOException {
        if (jp.currentToken() == JsonToken.VALUE_NULL) {
            return null;
        }
        return jp.getValueAsString();
    }

    private XmlConfigPropertyAdapted.ConfigPropertyType parseType(String typeString) {
        switch (typeString.toUpperCase()) {
            case "INTEGER":
                return XmlConfigPropertyAdapted.ConfigPropertyType.integerType;
            case "LONG":
                return XmlConfigPropertyAdapted.ConfigPropertyType.longType;
            case "DOUBLE":
                return XmlConfigPropertyAdapted.ConfigPropertyType.doubleType;
            case "FLOAT":
                return XmlConfigPropertyAdapted.ConfigPropertyType.floatType;
            case "BYTE":
                return XmlConfigPropertyAdapted.ConfigPropertyType.byteType;
            case "SHORT":
                return XmlConfigPropertyAdapted.ConfigPropertyType.shortType;
            case "BOOLEAN":
                return XmlConfigPropertyAdapted.ConfigPropertyType.booleanType;
            case "CHAR":
                return XmlConfigPropertyAdapted.ConfigPropertyType.charType;
            case "PASSWORD":
                return XmlConfigPropertyAdapted.ConfigPropertyType.passwordType;
            case "STRING":
            default:
                return XmlConfigPropertyAdapted.ConfigPropertyType.stringType;
        }
    }
}