/*******************************************************************************
 * Copyright (c) 2021, 2022 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Eurotech - initial API and implementation
 *******************************************************************************/
package org.eclipse.kapua.service.device.call.kura.model.configuration.json;
// Content with portions generated by generative AI platform

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.SerializerProvider;

import java.io.IOException;
import java.util.Arrays;
import java.util.Map;

import org.eclipse.kapua.commons.crypto.CryptoUtil;
import org.eclipse.kapua.locator.KapuaLocator;
import org.eclipse.kapua.service.device.call.kura.model.configuration.xml.KuraXmlConfigPropertiesAdapted;
import org.eclipse.kapua.service.device.call.kura.model.configuration.xml.KuraXmlConfigPropertiesAdapter;
import org.eclipse.kapua.service.device.call.kura.model.configuration.xml.XmlConfigPropertyAdapted;

/**
 * Custom JSON serializer for Kura configuration properties.<br>
 * This serializer converts the Map properties into a JSON structure that includes both the
 * property values and their corresponding types<br>
 * The resulting JSON adheres to the CONF-V2 format used in Kura, ensuring compatibility with Kura's configuration management.<br>
 * see https://esf.eurotech.com/docs/configuration-v2-rest-apis-and-conf-v2-request-handler#configurationproperties
 *
 * example JSON output for a property named "exampleProperty" of type INTEGER with value 42:
 * {
 *  "exampleProperty": {
 *  "value": 42,
 *  "type": "INTEGER"
 *  }
 *  }
 *
 * Internally, the serializer first converts the Map properties into an intermediate representation using XmlConfigPropertyAdapted objects, which are then serialized into the final JSON format.<br>
 * @since 2.1.0
 */
public class KuraJsonConfigPropertiesSerializer extends JsonSerializer<Map<String, Object>> {

    private static final String TYPE_FIELD_NAME_JSON = "type";
    private static final String VALUE_FIELD_NAME_JSON = "value";
    private final CryptoUtil cryptoUtil = KapuaLocator.getInstance().getComponent(CryptoUtil.class);

    @Override
    public void serialize(Map<String, Object> properties, JsonGenerator gen, SerializerProvider serializers) throws IOException {
        KuraXmlConfigPropertiesAdapted adapted = writeKuraPropertiesFromMap(properties);
        writeJsonStringFromKuraProperty(adapted, gen);
    }

    //read the map and creates the corresponding XmlConfigPropertyAdapted object
    private KuraXmlConfigPropertiesAdapted writeKuraPropertiesFromMap(Map<String, Object> properties) {
        try {
            return (new KuraXmlConfigPropertiesAdapter().marshal(properties));
        } catch (Exception e) {
            throw new IllegalArgumentException("Error marshalling wire graph configuration properties to XML adapted form", e);
        }
    }

    //from the XmlConfigPropertyAdapted object creates the JSON string (effective serialize/marshall)
    private void writeJsonStringFromKuraProperty(KuraXmlConfigPropertiesAdapted adapted, JsonGenerator gen) throws IOException {
        gen.writeStartObject();
        Arrays.stream(adapted.getProperties()).forEach(adaptedProperty -> {
            try {
                writeProperty(gen, adaptedProperty);
            } catch (IOException e) {
                throw new IllegalArgumentException("Error marshalling specific wire graph configuration property", e);
            }
        });
        gen.writeEndObject();
    }

    private void writeProperty(JsonGenerator gen, XmlConfigPropertyAdapted propertyAdapted) throws IOException {
        gen.writeObjectFieldStart(propertyAdapted.getName());
        gen.writeFieldName(VALUE_FIELD_NAME_JSON);

        String[] values = propertyAdapted.getValues();
        if (values == null || values.length == 0) {
            gen.writeNull();
            gen.writeStringField(TYPE_FIELD_NAME_JSON, "STRING");
            gen.writeEndObject();
            return;
        }

        XmlConfigPropertyAdapted.ConfigPropertyType type = propertyAdapted.getType();

        if (propertyAdapted.getArray()) {
            gen.writeStartArray();
            for (String value : values) {
                writeTypedValue(gen, value, type, propertyAdapted.isEncrypted());
            }
            gen.writeEndArray();
        } else {
            writeTypedValue(gen, values[0], type, propertyAdapted.isEncrypted());
        }

        gen.writeStringField(TYPE_FIELD_NAME_JSON, getTypeString(type));
        gen.writeEndObject();
    }

    private void writeTypedValue(JsonGenerator gen, String value, XmlConfigPropertyAdapted.ConfigPropertyType type, boolean isBase64Encrypted) throws IOException {
        if (value == null) {
            gen.writeNull();
            return;
        }

        switch (type) {
            case integerType:
                gen.writeNumber(Integer.parseInt(value));
                break;
            case longType:
                gen.writeNumber(Long.parseLong(value));
                break;
            case doubleType:
                gen.writeNumber(Double.parseDouble(value));
                break;
            case floatType:
                gen.writeNumber(Float.parseFloat(value));
                break;
            case byteType:
                gen.writeNumber(Byte.parseByte(value));
                break;
            case shortType:
                gen.writeNumber(Short.parseShort(value));
                break;
            case booleanType:
                gen.writeBoolean(Boolean.parseBoolean(value));
                break;
            case passwordType:
                if (isBase64Encrypted) { // if the original XmlConfigPropertyAdapted property is encrypted, we need to decode the value before writing it to JSON. (Kura expects the value plain text in JSON CONF-V2)
                    gen.writeString(cryptoUtil.decodeBase64(value));
                } else {
                    gen.writeString(value);
                }
                break;
            case charType:
            case stringType:
            default:
                gen.writeString(value);
                break;
        }
    }

    private String getTypeString(XmlConfigPropertyAdapted.ConfigPropertyType type) {
        switch (type) {
            case integerType: return "INTEGER";
            case longType: return "LONG";
            case doubleType: return "DOUBLE";
            case floatType: return "FLOAT";
            case byteType: return "BYTE";
            case shortType: return "SHORT";
            case booleanType: return "BOOLEAN";
            case charType: return "CHAR";
            case passwordType: return "PASSWORD";
            case stringType:
            default: return "STRING";
        }
    }
}
